DAILY_SUMMARY_COLUMNS = {
    "date": "TEXT PRIMARY KEY",
    "weight_kg": "REAL",
    "vo2_max": "REAL",
    "resting_hr": "INTEGER",
    "max_hr": "INTEGER",
    "total_steps": "INTEGER",
    "calories_active": "INTEGER",
    "intensity_minutes": "INTEGER",
    "sleep_duration_mins": "INTEGER",
    "sleep_score": "INTEGER",
    "sleep_deep_mins": "INTEGER",
    "sleep_light_mins": "INTEGER",
    "sleep_rem_mins": "INTEGER",
    "sleep_awake_mins": "INTEGER",
    "stress_stream": "TEXT",
    "body_battery_stream": "TEXT",
    "respiration_stream": "TEXT",
    "hrv_last_night_avg": "REAL",
    "hrv_weekly_avg": "REAL",
    "hrv_status": "TEXT",
    "training_status": "INTEGER",
    "training_status_feedback": "TEXT",
    "training_load_balance_feedback": "TEXT",
    "training_load": "REAL",
    "training_readiness": "INTEGER",
}

TABLE_COLUMNS = {
    "daily_summary": list(DAILY_SUMMARY_COLUMNS.keys()),
    "workouts": [
        "activity_id", "date", "sport", "name", "notes", "total_duration_mins",
        "distance_km", "avg_pace", "avg_hr", "max_hr", "avg_cadence",
        "elevation_gain", "elevation_loss", "steps", "calories", "zone1_mins",
        "zone2_mins", "zone3_mins", "zone4_mins", "zone5_mins", "hr_stream",
        "pace_stream", "elevation_stream", "cadence_stream", "moving_duration_mins",
        "elapsed_duration_mins", "avg_moving_pace", "downsampling_rate_secs",
    ],
    "strength_sets": [
        "activity_id", "set_order", "exercise_name", "category", "reps", "weight_kg", "duration_secs",
    ],
    "workout_routes": [
        "activity_id", "start_time_utc", "end_time_utc", "point_count", "start_lat",
        "start_lon", "end_lat", "end_lon", "min_lat", "max_lat", "min_lon",
        "max_lon", "center_lat", "center_lon", "sampled_points_json",
    ],
    "workout_weather": [
        "activity_id", "weather_source", "latitude", "longitude", "start_time_utc",
        "end_time_utc", "avg_temp_c", "min_temp_c", "max_temp_c",
        "avg_humidity_pct", "precipitation_mm", "rain_mm", "snowfall_mm",
        "avg_wind_kmh", "max_wind_gust_kmh", "weather_codes_json", "raw_hourly_json",
    ],
    "coach_decisions": [
        "decision_id", "date", "topic", "decision", "reason", "linked_activity_id",
        "linked_date", "status", "next_review_date", "created_at", "updated_at",
    ],
}

PRIMARY_KEYS = {
    "daily_summary": ["date"],
    "workouts": ["activity_id"],
    "strength_sets": ["activity_id", "set_order"],
    "workout_routes": ["activity_id"],
    "workout_weather": ["activity_id"],
    "coach_decisions": ["decision_id"],
}

DATE_COLUMNS = {
    "daily_summary": "date",
    "workouts": "date",
    "coach_decisions": "date",
}

DAILY_SUMMARY_SQL = """CREATE TABLE IF NOT EXISTS daily_summary (
        date                 TEXT PRIMARY KEY,
        weight_kg            REAL,
        vo2_max              REAL,
        resting_hr           INTEGER,
        max_hr               INTEGER,
        total_steps          INTEGER,
        calories_active      INTEGER,
        intensity_minutes    INTEGER,
        sleep_duration_mins  INTEGER,
        sleep_score          INTEGER,
        sleep_deep_mins      INTEGER,
        sleep_light_mins     INTEGER,
        sleep_rem_mins       INTEGER,
        sleep_awake_mins     INTEGER,
        stress_stream        TEXT,
        body_battery_stream  TEXT,
        respiration_stream   TEXT,
        hrv_last_night_avg   REAL,
        hrv_weekly_avg       REAL,
        hrv_status           TEXT,
        training_status      INTEGER,
        training_status_feedback TEXT,
        training_load_balance_feedback TEXT,
        training_load        REAL,
        training_readiness   INTEGER
    )"""

SCHEMA_SQL = [
    DAILY_SUMMARY_SQL,
    """CREATE TABLE IF NOT EXISTS workouts (
        activity_id           INTEGER PRIMARY KEY,
        date                  TEXT,
        sport                 TEXT,
        name                  TEXT,
        notes                 TEXT,
        total_duration_mins   REAL,
        distance_km           REAL,
        avg_pace              TEXT,
        avg_hr                INTEGER,
        max_hr                INTEGER,
        avg_cadence           INTEGER,
        elevation_gain        REAL,
        elevation_loss        REAL,
        steps                 INTEGER,
        calories              INTEGER,
        zone1_mins            INTEGER,
        zone2_mins            INTEGER,
        zone3_mins            INTEGER,
        zone4_mins            INTEGER,
        zone5_mins            INTEGER,
        hr_stream             TEXT,
        pace_stream           TEXT,
        elevation_stream      TEXT,
        cadence_stream        TEXT,
        moving_duration_mins  REAL,
        elapsed_duration_mins REAL,
        avg_moving_pace       TEXT,
        downsampling_rate_secs REAL
    )""",
    """CREATE TABLE IF NOT EXISTS strength_sets (
        activity_id     INTEGER,
        set_order       INTEGER,
        exercise_name   TEXT,
        category        TEXT,
        reps            INTEGER,
        weight_kg       REAL,
        duration_secs   INTEGER,
        PRIMARY KEY (activity_id, set_order)
    )""",
    """CREATE TABLE IF NOT EXISTS workout_routes (
        activity_id         INTEGER PRIMARY KEY,
        start_time_utc      TEXT,
        end_time_utc        TEXT,
        point_count         INTEGER,
        start_lat           REAL,
        start_lon           REAL,
        end_lat             REAL,
        end_lon             REAL,
        min_lat             REAL,
        max_lat             REAL,
        min_lon             REAL,
        max_lon             REAL,
        center_lat          REAL,
        center_lon          REAL,
        sampled_points_json TEXT,
        FOREIGN KEY(activity_id) REFERENCES workouts(activity_id)
    )""",
    """CREATE TABLE IF NOT EXISTS workout_weather (
        activity_id          INTEGER PRIMARY KEY,
        weather_source       TEXT,
        latitude             REAL,
        longitude            REAL,
        start_time_utc       TEXT,
        end_time_utc         TEXT,
        avg_temp_c           REAL,
        min_temp_c           REAL,
        max_temp_c           REAL,
        avg_humidity_pct     REAL,
        precipitation_mm     REAL,
        rain_mm              REAL,
        snowfall_mm          REAL,
        avg_wind_kmh         REAL,
        max_wind_gust_kmh    REAL,
        weather_codes_json   TEXT,
        raw_hourly_json      TEXT,
        FOREIGN KEY(activity_id) REFERENCES workouts(activity_id)
    )""",
    """CREATE TABLE IF NOT EXISTS coach_decisions (
        decision_id          INTEGER PRIMARY KEY AUTOINCREMENT,
        date                 TEXT NOT NULL,
        topic                TEXT NOT NULL,
        decision             TEXT NOT NULL,
        reason               TEXT,
        linked_activity_id   INTEGER,
        linked_date          TEXT,
        status               TEXT NOT NULL DEFAULT 'active'
                             CHECK(status IN ('active', 'resolved', 'superseded')),
        next_review_date     TEXT,
        created_at           TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at           TEXT,
        FOREIGN KEY(linked_activity_id) REFERENCES workouts(activity_id)
    )""",
]
