CREATE TABLE daily_summary (
        date                 TEXT PRIMARY KEY,
        weight_kg            REAL,
        vo2_max              REAL,
        resting_hr           INTEGER,
        max_hr               INTEGER,
        total_steps          INTEGER,
        calories_active      INTEGER,
        intensity_minutes    INTEGER,
        sleep_duration_mins  INTEGER,
        sleep_score          INTEGER,
        sleep_deep_mins      INTEGER,
        sleep_light_mins     INTEGER,
        sleep_rem_mins       INTEGER,
        sleep_awake_mins     INTEGER,
        stress_stream        TEXT,
        body_battery_stream  TEXT,
        respiration_stream   TEXT,
        hrv_last_night_avg   REAL,
        hrv_weekly_avg       REAL,
        hrv_status           TEXT,
        training_status      INTEGER,
        training_status_feedback TEXT,
        training_load_balance_feedback TEXT,
        training_load        REAL,
        training_readiness   INTEGER
    );
CREATE TABLE workouts (
        activity_id           INTEGER PRIMARY KEY,
        date                  TEXT,
        sport                 TEXT,
        name                  TEXT,
        notes                 TEXT,
        total_duration_mins   REAL,
        distance_km           REAL,
        avg_pace              TEXT,
        avg_hr                INTEGER,
        max_hr                INTEGER,
        avg_cadence           INTEGER,
        elevation_gain        REAL,
        elevation_loss        REAL,
        steps                 INTEGER,
        calories              INTEGER,
        zone1_mins            INTEGER,
        zone2_mins            INTEGER,
        zone3_mins            INTEGER,
        zone4_mins            INTEGER,
        zone5_mins            INTEGER,
        hr_stream             TEXT,
        pace_stream           TEXT,
        elevation_stream      TEXT,
        cadence_stream        TEXT,
        moving_duration_mins  REAL,
        elapsed_duration_mins REAL,
        avg_moving_pace       TEXT,
        downsampling_rate_secs REAL
    );
CREATE TABLE strength_sets (
        activity_id     INTEGER,
        set_order       INTEGER,
        exercise_name   TEXT,
        category        TEXT,
        reps            INTEGER,
        weight_kg       REAL,
        duration_secs   INTEGER,
        PRIMARY KEY (activity_id, set_order)
    );
CREATE TABLE workout_routes (
        activity_id         INTEGER PRIMARY KEY,
        start_time_utc      TEXT,
        end_time_utc        TEXT,
        point_count         INTEGER,
        start_lat           REAL,
        start_lon           REAL,
        end_lat             REAL,
        end_lon             REAL,
        min_lat             REAL,
        max_lat             REAL,
        min_lon             REAL,
        max_lon             REAL,
        center_lat          REAL,
        center_lon          REAL,
        sampled_points_json TEXT,
        FOREIGN KEY(activity_id) REFERENCES workouts(activity_id)
    );
CREATE TABLE workout_weather (
        activity_id          INTEGER PRIMARY KEY,
        weather_source       TEXT,
        latitude             REAL,
        longitude            REAL,
        start_time_utc       TEXT,
        end_time_utc         TEXT,
        avg_temp_c           REAL,
        min_temp_c           REAL,
        max_temp_c           REAL,
        avg_humidity_pct     REAL,
        precipitation_mm     REAL,
        rain_mm              REAL,
        snowfall_mm          REAL,
        avg_wind_kmh         REAL,
        max_wind_gust_kmh    REAL,
        weather_codes_json   TEXT,
        raw_hourly_json      TEXT,
        FOREIGN KEY(activity_id) REFERENCES workouts(activity_id)
    );
